### ISSUE TITLE
Question. Only Generate once

### ISSUE THREAD

**Issue by JeremyCarlsten** [fhoeben/hsac-fitnesse-plugin#10]
I would have assumed that if i define a randomBsn for example that it would generate once per test. 
ex. 
$define personId { !randomBSN }

|setup data|
|create person with Id|${personId}|

|some fixture|
|search for|${personId}|

what appears to be happening is two entirely different numbers being generated, what am I doing wrong?

**Comment by fhoeben** [comment]
Your '!define' in effect creates a call to the random number generator, so each time it is placed in the wiki a new number is generated. 
This can sometimes also be too few times. For instance when the call is placed inside a scenario table (not in parameter to that scenario but in the scenario's content) it called only once (for the definition of the scenario) and not anew for each scenario invocation.

In you situation I would recommend you call the generator once, and place its outcome in a 'Slim symbol/variable' and then reference that symbol when you want to use that randomly generated value. There are multiple fixtures than can help you achieve this, and its also very easy to write your own. FitNesse comes with an 'echo fixture' which can do this for you, or in my fixtures you could use my 'string fixture'.

You get something like
```
|script|echo fixture|
|$personId=|echo|!randomBSN|

|setup data|
|create person with Id|$personId|

|some fixture|
|search for|$personId|
```

**Comment by JeremyCarlsten** [comment]
We don't actually use slim, I'm thinking I should be able to figure it out though. 

Thanks.
