### ISSUE TITLE
to check the <a> tag behind a screen link

### ISSUE THREAD

**Issue by keetron** [fhoeben/hsac-fitnesse-plugin#12]
Feature request: To have a command that will check the `<a>` tag behind an element.
Right now I click on a link, verify the tab URL, click back and continue whatever it was I wanted done. It would be better to have:
`|check|somescreenthing|link value for|http://awesomedomaingoeshere.com|`
Which would return true if they match.
Alternatively, a command to read the `<a>` tag:
`|link value for|somescreenthing|`

Maybe both?

In a way, this is a to-do list for myself to remind me what I want added.

**Comment by fhoeben** [comment]
I believe this is a feature request for BrowserTest?

Please use: https://github.com/fhoeben/hsac-fitnesse-fixtures/issues
