### ISSUE TITLE
Count the occurrences of a screen element or text

### ISSUE THREAD

**Issue by keetron** [fhoeben/hsac-fitnesse-plugin#13]
I would love to have some sort of counter for screen texts

```
|check count|1|for|HeDoesntLookLikeAToad|
|check count|3|for|ItGotBetter|
```

both would return true or false.

and alternatively or additional

`|count|HeDoesntLookLikeAToad|`
would return 1

`|check count|3|for|ItGotBetter|`
would return 3

Same as my other issues, a small to do list for myself for things to add to HSAC.

**Comment by fhoeben** [comment]
I believe this is a feature request for BrowserTest?

Please use: https://github.com/fhoeben/hsac-fitnesse-fixtures/issues
