### ISSUE TITLE
Error trying to run against ios-driver

### ISSUE THREAD

**Issue by sglebs** [fhoeben/hsac-fitnesse-plugin#2]
Hi,

I am trying this:

```
!|script | selenium driver setup |
| connect to driver at | ${url} | with capabilities | device:iphone,language:en,locale:en_US,CFBundleName:InternationalMountains,simulator:true,variation:iPhone5s,instruments:true |

|script      | browser test                                                          |
|click       | Mountain 1   
```

but I get this error back:  The server cannot run Capabilities [{locale=en_GB}] at the moment.you need to specify the bundle to test

If I try the same thing with my own (investigation) fixture https://github.com/sglebs/BetDevFitNesse/blob/master/src/main/java/net/betterdeveloper/fitnesse/RemoteWebDriverFixture.java it works. Like this:

|import|
|net.betterdeveloper.fitnesse|

|library |
|Remote Web Driver Fixture |

```
| script |
| start on | ${url} | with capabilities | {"device" : "iphone", "language": "en", "locale": "en_US", "CFBundleName": "InternationalMountains", "simulator": "true", "variation":"iPhone5s", "instruments": "true"} |
| click on element with xpath | //UIATableCell[contains(@name,'Mountain 5')] |
| stop |
```

Did I miss anything on the capabilities setup with your fixture or is it a limitation? Thanks!

**Comment by fhoeben** [comment]
Am I right to think this is actually about https://github.com/fhoeben/hsac-fitnesse-fixtures (and not the plugin)?

I have not tried this specifically with an ios driver, but I'm surprised at the error since you seem to indicate en_US and not en_GB.
When does the exception occur, or the `connect to driver at`? 

I'll try to look into this with more detail later.

**Comment by fhoeben** [comment]
It turns out I never tested specifying the capabilities in the wiki (only when running inside an maven integration test using the system property to specify the capabilities). The capabilities you specify at the moment don't get parsed at all, so are not used to connect!

I apologize. I will have a fix for you shortly.

**Comment by fhoeben** [comment]
Passing the capabilities requires you to use FitNesse's [hashTable markup](http://fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.FitNesseWiki.MarkupLanguageReference.MarkupHashTable) to specify
 them.
Try changing the first table to
```
|script              |selenium driver setup                                                                                                    |
|connect to driver at|${url}|with capabilities|!{device:iphone,language:en,locale:en_US,CFBundleName:!-InternationalMountains-!,simulator:true,variation:iPhone5s,instruments:true}|
```

Please note I no longer have the `!` before the first pipe of the table, and there are `!-` and `-!` around InternationalMountains... 

That should give you behavior similar to your own fixture, correct?

**Comment by sglebs** [comment]
Do I need to got pull any code or just the hash table markup does it? (Not at the computer now)

**Comment by fhoeben** [comment]
No need to do a Git pull, just the improved markup.
(I did update the example SuiteSetUp page to have the proper hashtable markup)

**Comment by sglebs** [comment]
The improved markup did not do it for me. I did a git pull and let's see if it now works.

**Comment by sglebs** [comment]
The git pull did not do it. Then I found a tiny typo in the copy/paste (my bad). It now works! Thanks!

And sorry for entering the issue against the wrong thing. I had 2 tabs open and made a mistake :-/
