### ISSUE TITLE
Random French IBAN should use better 'guichet' codes

### ISSUE THREAD

**Issue by fhoeben** [fhoeben/hsac-fitnesse-plugin#23]
At the moment a random French iban has a random 'codeGuichet', and selects a bank code from a list of 4 codes.
Not all guichets are in use. Combinations should be used which are valid. Being complete is probably not possible, but guichet '00001' is in use by at least the following banks:

10008
10088
10096
10178
10206
10207
10218
10273
10343
10548
10550
10773
10800
10807
10900
10907
10918
10930
11128
11138
11140
11188
11190
11206
11210
11230
11238
11307
11315
11343
11353
11380
11438
11449
11470
11478
11490
11518
11678
11706
11720
11769
11790
11830
11833
11938
11978
11989
12008
12043
12050
12083
12088
12110
12128
12138
12148
12179
12249
12258
12280
12298
12308
12318
12338
12398
12406
12418
12438
12453
12468
12478
12549
12558
12579
12589
12619
12658
12670
12748
12749
12818
12828
12869
12879
12906
12938
12978
13018
13028
13038
13118
13128
13150
13158
13168
13179
13188
13220
13369
13379
13400
13408
13473
13490
13506
13528
13538
13539
13540
13558
13579
13580
13606
13648
13678
13698
13728
13758
13769
13773
13798
13838
13858
13878
13888
13906
13907
13959
13998
14018
14020
14108
14110
14120
14139
14173
14198
14218
14228
14328
14378
14388
14398
14408
14410
14448
14500
14505
14506
14568
14578
14588
14628
14633
14643
14648
14658
14670
14688
14690
14706
14707
14758
14768
14773
14800
14806
14879
14888
14940
14948
14958
14989
14998
15008
15068
15078
15128
15149
15160
15173
15218
15243
15250
15258
15273
15278
15298
15338
15348
15378
15380
15389
15408
15428
15429
15448
15488
15498
15548
15568
15573
15607
15608
15628
15648
15668
15673
15708
15728
15818
15843
15858
15868
15898
15900
15958
15960
15970
15978
15980
16000
16020
16030
16048
16050
16088
16106
16130
16160
16190
16218
16243
16253
16270
16278
16298
16348
16373
16378
16408
16418
16443
16473
16478
16518
16558
16588
16598
16606
16607
16608
16618
16638
16640
16643
16678
16700
16706
16718
16738
16760
16768
16773
16778
16780
16798
16807
16808
16820
16839
16843
16850
16870
16906
16933
16943
16979
16989
17060
17106
17153
17173
17206
17273
17290
17373
17453
17473
17519
17549
17599
17607
17619
17629
17649
17660
17779
17789
17807
17839
17873
17919
17979
17989
18020
18029
18040
18043
18059
18089
18169
18179
18180
18206
18209
18233
18280
18289
18306
18329
18343
18370
18429
18473
18529
18530
18540
18553
18569
18589
18609
18610
18650
18660
18669
18689
18707
18709
18769
18869
18919
18930
18973
18979
18989
19000
19053
19063
19069
19106
19139
19150
19169
19173
19230
19250
19253
19259
19269
19400
19406
19443
19479
19519
19530
19553
19560
19570
19730
19733
19850
19870
19940
19973
19990
20019
20041
20280
20290
21339
21349
21570
21670
21859
21990
22840
22910
22970
23380
23779
23890
23930
24280
24599
24659
25609
25709
26269
26310
26679
26819
27589
28310
28860
30006
30258
30438
30478
30568
30588
30628
30748
40031
40238
40978
41139
41189
41249
41329
41639
41829
42529
42559
42649
43030
43199
43629
43789
43799
43899
44149
44729
45030
45159
45189
45280
45288
45340
45418
45598
45850
60011
60080
60220
74202

**Comment by keetron** [comment]
Yeah, the bankcodrs are a pain ;-)

Op 20 okt. 2017 16:07 schreef "Fried Hoeben" <notifications@github.com>:
