### ISSUE TITLE
REQ: Nested table templates

### ISSUE THREAD

**Issue by teunisnl** [fhoeben/hsac-fitnesse-plugin#27]
**What:**
```
|table template|T1   |
|echo          |@{P3}|
|echo          |@{P1}|

|table template|T2   |
|T1                  |
|echo          |@{P2}|

|script|echo fixture|

|T2      |
|P1|P2|P3|
|1 |2 |3 |
```

**Why:**
Alot more flexible, and less maintaining of tests; 
Downside would be that names have to be unique over multiple templates
(current main reason need to add products, but in other test I need to remove products too, would like reuse the adding part)

**Current work around:**
```
|table template|T1   |
|echo          |@{P3}|
|echo          |@{P1}|

|table template       |T2         |
|T1                  ;|@{P3}|@{P1}|
|echo                 |@{P2}      |

|script|echo fixture|

|T2      |
|P1|P2|P3|
|1 |2 |3 |
```

**Comment by fhoeben** [comment]
I see why this can be useful. Would it be acceptable if:
- order of table template definition is important (i.e. template used as nested has to be defined first)
- call to nested table template must end with ';' (e.g. not `T1` but `T1;`)
- no explicit parameters are allowed

**Comment by fhoeben** [comment]
I believe I can address this request. But I fear a FitNesse update is needed. See https://github.com/unclebob/fitnesse/pull/1103

**Comment by fhoeben** [comment]
Given the 3 limitations stated above I created a rough version of a fix
https://github.com/fhoeben/hsac-fitnesse-plugin/tree/tableTemplateNested

**Comment by teunisv** [comment]
This is for totally acceptable, an improvement would be to remove  the limitation:
> order of table template definition is important (i.e. template used as nested has to be defined first)
Is my assumption right that this also requires that the nested table templates would need to be defined in the same scenariolibrary  ?

**Comment by fhoeben** [comment]
I don't think I know straight away how to remove that limitation. I believe I need to determine the parameters when the table is parsed, which requires the 'called table' to be parsed before this one.

I don't think it has to be in the same scenario library. I believe a higher level scenario library (i.e. in a parent suite) would also work.

**Comment by teunisv** [comment]
The current solution is enough for me; 
if at another point the order limitation can be removed that would be an great improvement,
but for readability i think current required order is actually better.

**Comment by teunisv** [comment]
> I believe I can address this request. But I fear a FitNesse update is needed. See unclebob/fitnesse#1103

https://bintray.com/fitnesse/release/fitnesse/20171015 ?

**Comment by teunisv** [comment]
> I believe I can address this request. But I fear a FitNesse update is needed. See unclebob/fitnesse#1103

https://bintray.com/fitnesse/release/fitnesse/20171015 ?

**Comment by fhoeben** [comment]
I implemented a workaround (by using some reflection) so the change is not REQUIRED.
But I believe a new release is around the corner...
