### ISSUE TITLE
"define table type" with storyboard makes 1 failed test abort the entire suite

### ISSUE THREAD

**Issue by sglebs** [fhoeben/hsac-fitnesse-plugin#3]
Hi @fhoeben 

I am helping a friend migrate from xebium to hsac. He is using your bridge for now, but hit another snag. He has this:

```
| define table type |
| caso de teste | as script |
```
In this case, if 1 test fails, the rest of the suite keeps running fine. So far so good. He then went ahead and changed things to:

```
| define table type |
| caso de teste | as storyboard |
```
In this case, if 1 test fails, the rest of the suite also fails, with "Test not run".

He really wants to use storyboard and he really wants to be able to use "define table type".

I was able to reproduce it with a little suite of 4 tests. I can share that if you want, as a zip.

**Comment by sglebs** [comment]
I think I will have to take it back. I can no longer reproduce this. I will keep trying a bit more.

**Comment by sglebs** [comment]
Can't reproduce.

**Comment by fhoeben** [comment]
All I can think of was that that a StopSuiteException was thrown somewhere: that would cause the rest of the suite not to be executed (similar to the described behavior for an exception containing StopTest in its name in http://www.fitnesse.org/FitNesse.UserGuide.WritingAcceptanceTests.SliM.ExceptionHandling). I'm not aware my code throws these anywhere...

All the documentation for StopSuite I can find is in the acceptance tests: http://www.fitnesse.org/FitNesse.SuiteAcceptanceTests.SuiteSlimTests.StopSuite
