### ISSUE TITLE
Table template breaks when using var in column 4

### ISSUE THREAD

**Issue by lennyg1** [fhoeben/hsac-fitnesse-plugin#34]
Since 1.26 the following table template gives me an error; **imbroken: Bad table! The argument somelocation is not an input to the scenario.**

```
|scenario|click something|something|in something else|else|
|click   |@{something}   |in       |@{else}               |

!|table template|imbroken                                      |
|click something|FitNesse    |in something else|@{somelocation}|
|enter          |@{something}|as               |@{someplace}   |

|script|browser test         |
|open  |http://localhost:9090|

|imbroken                                               |
|something|someplace      |somelocation                 |
|searchy  |Search for page|id=WelcometoFitNesse.FitNesse|
```

It seems to be caused by the @{somelocation} passing through to a scenario underneath.

**Comment by maikelgithub** [comment]
Hi @lennyg1 

We are having the same issues with our scripts. It's the combination of retrieving variables that @tcnh decribes in [this thread](https://github.com/unclebob/fitnesse/pull/1178#issuecomment-458550352) and I've described [here](https://github.com/unclebob/fitnesse/pull/1178#issuecomment-483527998). 

@fhoeben is there any way to make the scripts work again? almost all our scripts are still failing so we're now bound to use an older version of fitnesse :(

**Comment by tcnh** [comment]
I believe this happens when a template calls a scenario using an input parameter and the scenario has a different name for this parameter.

See #35 for what I think fixes this issue

**Comment by lennyg1** [comment]
My table templates seem to work again with the latest release (1.27)
