### ISSUE TITLE
Please add debug functionality to "table template" , similar to "debug script"

### ISSUE THREAD

**Issue by pvbemmelen62** [fhoeben/hsac-fitnesse-plugin#43]
I would like to be able to step through the lines of a table template: before each line is executed, a pause popup should be shown with the text of the line about to be executed.
That would be somewhat similar to the behaviour of a "debug script" table; but different, because

|debug script|
|show|echo|mama|
|show|echo|papa|

would step through the two show echo lines,
whereas

|create person|
|name|birthdate|address|
|sammy|2020-01-02|Sunny Vale, Backstreet 2|
|johnny|2021-03-04|Sunny Vale, Backstreet 4|

would step for each line above, through the lines defined in

|table template|create person|
|process name|$name|
|process address|$address|
|process birthdate|$birthdate|

I've asked this question also on
https://github.com/praegus/toolchain-fitnesse-plugin/issues/33
but got no response; maybe I should have asked it here, under fhoeben.

For reference:

https://github.com/fhoeben/hsac-fitnesse-plugin/wiki/2.-Table-Template-Example

https://github.com/praegus/toolchain-fitnesse-plugin
Pausing table
Usage
| debug script | instead of | script | This will pause execution before each script table row and prompt the user to continue of stop the test, informing the user what the next instruction will be.

**Comment by fhoeben** [comment]
@tcnh can you help @pvbemmelen62 ?

I never used the debug script feature of the praegus toolchain. I would just run the test page via my Java debugger (using [`FixtureDebugTest`](https://github.com/fhoeben/hsac-fitnesse-fixtures/blob/master/src/test/java/nl/hsac/fitnesse/fixture/FixtureDebugTest.java), replace 'HsacAcceptanceTests.SlimTests.UtilityFixtures' with the correct test) and place breakpoints at the appropriate methods of my fixtures being called.

**Comment by tcnh** [comment]
Just replace `script` before the table template call with `debug script`. This will step through the table template script line by line.

**Comment by tcnh** [comment]
I can see how it may be surprising, but to call a template table you already have to be using a ScriptTableActor (this can be any script table, so it may also be a scenario, other table template, or - a debug script table or any other script table extension)

**Comment by pvbemmelen62** [comment]
Is it the ScriptTableActor that is responsible for the debug behaviour ? I assumed it was the table type that implements the debug behaviour.

A scenario doesn't allow you to specify a table actor .  Nor does a table template. So somewhere preceding them, there must always be a "script" or "debug script" table.  Is that right ?

How can I definitively determine whether a certain table type is an extension of a script table ?
