### ISSUE TITLE
Validating HTML

### ISSUE THREAD

**Issue by violinner** [fhoeben/hsac-fitnesse-plugin#9]
The browser test "save page source" command can be used accumulate the current state of dynamic web pages after different user actions, then evaluated individually or in a batch with a fixture that calls an HTML validator (https://github.com/validator) as a library.

Is there an existing extension that does HTML validation fluidly -- especially with the ability to selectively ignore some errors?

**Comment by fhoeben** [comment]
Nothing yet. I image it would not be hard to add in a subclass of BrowserTest: either override the current behaviour of "save page source", or add a new method ("validate page source"?) that first calls the save... method and then validates the created file.

**Comment by fhoeben** [comment]
I believe this is a feature request for BrowserTest?

Please use: https://github.com/fhoeben/hsac-fitnesse-fixtures/issues
